version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
  tcc: atomicjar/testcontainers-cloud-orb@0.1.0
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor:
            name: maven/default
            tag: "21.0"
          pre-steps:
            - tcc/setup
