version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
jobs:
  build:
    executor:
      name: maven/default
      tag: "21.0"
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: "./mvnw verify"
